# Generated by Django 3.2.6 on 2021-08-17 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_auto_20210809_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 17, 7, 30, 58, 99923), null=True),
        ),
    ]
