# Generated by Django 3.2.6 on 2021-08-17 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_query_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='datetime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
