# Generated by Django 3.2.3 on 2021-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_alter_query_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True),
        ),
    ]
