# Generated by Django 3.2.5 on 2021-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_alter_studentcoursedata_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batchcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
