# Generated by Django 3.2.5 on 2021-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_batch_batchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_enrolled',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='now_attending',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
